image: node:latest

before_script:
  - npm install

cache:
  key: "$CI_COMMIT_REF_SLUG.$NODE_VERSION"
  paths:
  - node_modules/

test_all:
  script:
   - npm test

test_lint:
  script:
   - npm run lint
