language: node_js
node_js:
 - "6"
 - "8"
 - "node"
script:
  - npm run lint
  - npm test
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
